[package]
name = "dimdimmuscuback"
version = "0.1.0"
edition = "2021"

[dependencies]
lib-auth = { path = "../libs/lib-auth" }

axum = "0.7.4"

shuttle-axum = "0.41.0"
shuttle-runtime = "0.41.0"
shuttle-shared-db = { version = "0.41.0", features = ["postgres", "sqlx"] }

tokio = "1.36.0"

sqlx = { version = "0.7.4", features = ["runtime-tokio-native-tls", "postgres"] }

serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.114"

chrono = "0.4.35"

tracing-subscriber = "0.3.18"
tracing = "0.1.40"

uuid = { version = "1.7.0", features = ["v4"] }


tower-cookies = "0.10"