[package]
name = "hand_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.3", features = ["json"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }