[env]
# -- Service Environment Variables
# IMPORTANT:
#   For cargo commands only.
#   For deployed env, should be managed by container
#   (e.g., Kubernetes).

## -- Secrets
# Keys and passwords below are for localhost dev ONLY.
# e.g., "welcome" type of passwords.
# i.e., Encryption not needed.

DIMDIMMUSCU_SERVICE_PWD_KEY = "CKUGFOD9_2Qf6Pn3ZFRYgPYb8ht4vKqEG9PGMXTB7497bT0367DjoaD6ydFnEVaIRda0kKeBZVCT5Hb62m2sCA"
DIMDIMMUSCU_SERVICE_TOKEN_KEY = "9FoHBmkyxbgu_xFoQK7e0jz3RMNVJWgfvbVn712FBNH9LLaAWS3CS6Zpcg6RveiObvCUb6a2z-uAiLjhLh2igw"
DIMDIMMUSCU_SERVICE_TOKEN_DURATION_MS = "1800000" # 30 minutes
