//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sets")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub lift_id: i32,
    pub set_number: i32,
    pub weight: i32,
    pub rep: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::lifts::Entity",
        from = "Column::LiftId",
        to = "super::lifts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Lifts,
}

impl Related<super::lifts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lifts.def()
    }
}
